services:
  db:
    container_name: ru-facil-db
    image: postgres:13
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-ru-facil:/var/lib/postgresql/data
    networks:
      - ru-facil-network
  web:
    container_name: ru-facil-web
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - db
    networks:
      - ru-facil-network
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET
      - NODE_ENV
      - EFI_CLIENT_ID_DEV
      - EFI_CLIENT_SECRET_DEV
      - EFI_BASE_URL_DEV
      - EFI_CERT_DEV
      - EFI_CLIENT_ID_PROD
      - EFI_CLIENT_SECRET_PROD
      - EFI_BASE_URL_PROD
      - EFI_CERT_PROD
      - PIX_KEY
      - TICKET_UNIT_PRICE
      - EMAIL_USER
      - EMAIL_PASSWORD
      - EMAIL_SERVICE
      - EMAIL_TOKEN_SECRET
      - OAUTH_CLIENTID
      - OAUTH_CLIENT_SECRET
      - OAUTH_REFRESH_TOKEN
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  postgres-ru-facil:

networks: 
  ru-facil-network:
    driver: bridge
